# 服务端口
server:
  port: 8088

spring:
  # 服务名
  application:
    name: service-acl
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?serverTimezone=GMT%2B8&userUnicode=true&characterEncoding=utf-8
    username: root
    password: password
  #   返回JSON的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  # 指定注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


# mybatis-plus的日志
mybatis-plus:
  mapper-locations: classpath:com/yww/aclservice/mapper/xml/*.xml



